services:
  nextcloud-app:
    container_name: nextcloud-app
    image: 'nextcloud:latest'
    restart: always
    ports:
      - '30012:80'
    volumes:
      - /homelab/nextcloud/nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=Passw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https
    depends_on:
      - nextcloud-db
    networks:
      - frontend
      - backend


  nextcloud-db:
    container_name: nextcloud-db
    image: 'yobasystems/alpine-mariadb:latest'
    restart: always
    ports:
      - '3306:3306'
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /homelab/nextcloud/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - MYSQL_PASSWORD=Passw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
networks:
  frontend:
  backend:
